const dotenv = require("dotenv").config();
const { GoogleGenAI } = require("@google/genai");
const { z } = require("zod");
const puppeteer = require("puppeteer-core");

const apiKey =
    process.env.GOOGLE_GENAI_API_KEY ||
    process.env.GEMINI_API_KEY ||
    process.env.GOOGLE_API_KEY;

if (!apiKey) {
    throw new Error("Missing Gemini API key. Set GOOGLE_GENAI_API_KEY in Backend/.env.");
}

const ai = new GoogleGenAI({ apiKey });

const interviewReportSchema = z.object({
    matchScore: z.number().describe("The match score between 0 and 100 indicating how well the candidate's profile matches the job description"),
    technicalQuestions: z.array(z.object({
        question: z.string().describe("Technical question can be asked in interview"),
        intention: z.string().describe("The intention of interviewer behind asking this question"),
        answer: z.string().describe("How to answer this question, what points to cover, what approach to take etc.")
    })).describe("Technical question that can be asked in interview along with their intention and how to answer it"),
    behaviourQuestions: z.array(z.object({
        question: z.string().describe("Behaviour question can be asked in interview"),
        intention: z.string().describe("The intention of interviewer behind asking this question"),
        answer: z.string().describe("How to answer this question, what points to cover, what approach to take etc.")
    })).describe("Behaviour question that can be asked in interview along with their intention and how to answer it"),
    skillGaps: z.array(z.object({
        skill: z.string().describe("Skill gap can be asked in interview"),
        severity: z.enum(["low", "medium", "high"]).describe("The severity of skill gap"),
    })).describe("List of skill gaps in the candidate's profile along with their severity"),
    preparationPlan: z.array(z.object({
        day: z.number().describe("The day number in the preparation plan, starting from 1"),
        focus: z.string().describe("The main focus of this day in the preparation plan, e.g. data structure"),
        task: z.array(z.string()).describe("List of tasks to be completed in this day in the preparation plan, e.g. implement a binary search tree")
    })).describe("A day-wise preparation plan for the candidate to prepare for the interview"),
    title: z.string().describe("The title of the interview report, e.g. Software Engineer Interview Report"),
});

const interviewReportJsonSchema = z.toJSONSchema(interviewReportSchema);

async function generateInterviewReport({ resume, jobDescription, selfDescription }) {

    const prompt = `Generate an interview report for a candidate with the following details:
    Resume: ${resume}
    Job description: ${jobDescription}
    Self description: ${selfDescription}`;

    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash-lite",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseJsonSchema: interviewReportJsonSchema,
        }
    });

    return JSON.parse(response.text)

}

async function generateResumePdf({ resume,selfDescription,jobDescription }) {
    const resumePdfSchema = z.object({
        html: z.string().describe("The HTML content of the resume which can be converted to PDF using any library like puppeteer")
    })

    const promt = `Generate resume for a candidate with the following details:
    Resume: ${resume}
    Job description: ${jobDescription}
    Self description: ${selfDescription}
    
    the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
    The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
    The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
    you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
    The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
    The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.`

    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash-lite",
        contents: promt,
        config: {
            responseMimeType: "application/json",
            responseJsonSchema: z.toJSONSchema(resumePdfSchema),
        }
    })

    const jsonContent = JSON.parse(response.text)
    
    const pdfBuffer = await generatePdfFromHtml(jsonContent.html)

    return pdfBuffer
}

async function generatePdfFromHtml(htmlContent) { 
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: "networkidle0" });

    const pdfBuffer = await page.pdf({
        format: "A4", margin: {
            top: "20mm",
            bottom: "20mm",
            left: "15mm",
            right: "15mm"
    } });
    await browser.close();
    return pdfBuffer;
}

module.exports = { generateInterviewReport, generateResumePdf, generatePdfFromHtml };

//Just import the invokeGeminiAi function and call it in server.js, it will invoke the ai..
//Content is the question that you want to ask to the AI inshort it is the prompt   

/*
If the error is raising that your quota has reached the limit then the free use of the ai is over you need to change it from the below link
https://ai.google.dev/gemini-api/docs/models

Few models
gemini-2.5-flash-lite
gemini-2.5

If the error is raising that your API key is invalid and it is leaked then we need to change the .env file means github is an open platform so anyone can use our link so 
we need to put the .env file in the .gitignore file so it will not be pushed to github..
*/
